services:
  - type: web
    name: fintech-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_BASE_URL
        value: https://fintech-backend-f9vu.onrender.com/api/v1
      - key: VITE_DEV_MODE
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
